BOOM_OS_ID="3ee2c8b6e7b5043d305bc2850ba01f4838739a1b"
BOOM_OS_NAME="NoOptions"
BOOM_OS_SHORT_NAME="nooptions"
BOOM_OS_VERSION="1 (Server)"
BOOM_OS_VERSION_ID="1"
BOOM_OS_UNAME_PATTERN="no1"
BOOM_OS_KERNEL_PATTERN="/vmlinux-%{version}"
BOOM_OS_INITRAMFS_PATTERN="/initramfs-%{version}.img"
BOOM_OS_ROOT_OPTS_LVM2="rd.lvm.lv=%{lvm_root_lv}"
BOOM_OS_ROOT_OPTS_BTRFS="rootflags=%{btrfs_subvolume}"
BOOM_OS_OPTIONS=""
