BOOM_OS_ID="28851f93a99cad97a0082fcd0270da994b2bff7a"
BOOM_OS_NAME="NewOs"
BOOM_OS_SHORT_NAME="newos"
BOOM_OS_VERSION="1 (Server Edition)"
BOOM_OS_VERSION_ID="1"
BOOM_OS_UNAME_PATTERN="no1"
BOOM_OS_KERNEL_PATTERN="/vmlinuz-%{version}"
BOOM_OS_INITRAMFS_PATTERN="/initramfs-%{version}.img"
BOOM_OS_ROOT_OPTS_LVM2="rd.lvm.lv=%{lvm_root_lv}"
BOOM_OS_ROOT_OPTS_BTRFS="rootflags=%{btrfs_subvolume}"
BOOM_OS_OPTIONS="root=%{root_device} ro %{root_opts}"
