BOOM_OS_ID="9736c347ccb724368be04e51bb25687a361e535c"
BOOM_OS_NAME="Fedora"
BOOM_OS_SHORT_NAME="fedora"
BOOM_OS_VERSION="25 (Server Edition)"
BOOM_OS_VERSION_ID="25"
BOOM_OS_UNAME_PATTERN="fc25"
BOOM_OS_KERNEL_PATTERN="/vmlinuz-%{version}"
BOOM_OS_INITRAMFS_PATTERN="/initramfs-%{version}.img"
BOOM_OS_ROOT_OPTS_LVM2="rd.lvm.lv=%{lvm_root_lv}"
BOOM_OS_ROOT_OPTS_BTRFS="rootflags=%{btrfs_subvolume}"
BOOM_OS_OPTIONS="root=%{root_device} ro %{root_opts} rhgb quiet"
