BOOM_OS_ID="418203ef8b710a2dc125676933747d9c893374db"
BOOM_OS_NAME="Ubuntu"
BOOM_OS_SHORT_NAME="ubuntu"
BOOM_OS_VERSION="17.04 (Zesty Zapus)"
BOOM_OS_VERSION_ID="17.04"
BOOM_OS_UNAME_PATTERN="generic"
BOOM_OS_KERNEL_PATTERN="/vmlinuz-%{version}"
BOOM_OS_INITRAMFS_PATTERN="/initramfs-%{version}.img"
BOOM_OS_ROOT_OPTS_LVM2="rd.lvm.lv=%{lvm_root_lv}"
BOOM_OS_ROOT_OPTS_BTRFS="rootflags=%{btrfs_subvolume}"
BOOM_OS_OPTIONS="root=%{root_device} ro %{root_opts}"
