BOOM_OS_ID="3fc389bba581e5b20c6a46c7fc31b04be465e973"
BOOM_OS_NAME="Red Hat Enterprise Linux Server"
BOOM_OS_SHORT_NAME="rhel"
BOOM_OS_VERSION="7.2 (Maipo)"
BOOM_OS_VERSION_ID="7.2"
BOOM_OS_UNAME_PATTERN="el7"
BOOM_OS_KERNEL_PATTERN="/vmlinuz-%{version}"
BOOM_OS_INITRAMFS_PATTERN="/initramfs-%{version}.img"
BOOM_OS_ROOT_OPTS_LVM2="rd.lvm.lv=%{lvm_root_lv}"
BOOM_OS_ROOT_OPTS_BTRFS="rootflags=%{btrfs_subvolume}"
BOOM_OS_OPTIONS="root=%{root_device} ro %{root_opts} rhgb quiet"
BOOM_OS_OPTIONAL_KEYS="grub_users grub_arg grub_class"
