BOOM_OS_ID="81a78ae30161f02d8b2e6092bde6b789d9a3c21b"
BOOM_OS_NAME="Ubuntu"
BOOM_OS_SHORT_NAME="ubuntu"
BOOM_OS_VERSION="14.04.4 LTS, Trusty Tahr"
BOOM_OS_VERSION_ID="14.04"
BOOM_OS_UNAME_PATTERN="generic"
BOOM_OS_KERNEL_PATTERN="/vmlinuz-%{version}"
BOOM_OS_INITRAMFS_PATTERN="/initramfs-%{version}.img"
BOOM_OS_ROOT_OPTS_LVM2="rd.lvm.lv=%{lvm_root_lv}"
BOOM_OS_ROOT_OPTS_BTRFS="rootflags=%{btrfs_subvolume}"
BOOM_OS_OPTIONS="root=%{root_device} ro %{root_opts}"
