BOOM_OS_ID="987f0daf2d004093d71ca678fea89ef1989695b3"
BOOM_OS_NAME="NoBTRFS"
BOOM_OS_SHORT_NAME="nobtrfs"
BOOM_OS_VERSION="1 (Server)"
BOOM_OS_VERSION_ID="1"
BOOM_OS_UNAME_PATTERN="nb1"
BOOM_OS_KERNEL_PATTERN="/vmlinux-%{version}"
BOOM_OS_INITRAMFS_PATTERN="/initramfs-%{version}.img"
BOOM_OS_ROOT_OPTS_LVM2="rd.lvm.lv=%{lvm_root_lv}"
BOOM_OS_ROOT_OPTS_BTRFS="rootflags=%{btrfs_subvolume}"
BOOM_OS_OPTIONS="root=%{root_device}"
