BOOM_OS_ID="bab31a35db247122f05658a2721f53c3aae4a039"
BOOM_OS_NAME="Foo"
BOOM_OS_SHORT_NAME="foo"
BOOM_OS_VERSION="1 (Server)"
BOOM_OS_VERSION_ID="1"
BOOM_OS_UNAME_PATTERN="fo1"
BOOM_OS_KERNEL_PATTERN="/vmlinuz-%{version}"
BOOM_OS_INITRAMFS_PATTERN="/initramfs-%{version}.img"
BOOM_OS_ROOT_OPTS_LVM2="rd.lvm.lv=%{lvm_root_lv}"
BOOM_OS_ROOT_OPTS_BTRFS="rootflags=%{btrfs_subvolume}"
BOOM_OS_OPTIONS="root=%{root_device} ro %{root_opts}"
