BOOM_OS_ID="d3e1bd82b33d0b1da75f0e893d5a30db8e308b58"
BOOM_OS_NAME="NoLVM"
BOOM_OS_SHORT_NAME="nolvm"
BOOM_OS_VERSION="1 (Server)"
BOOM_OS_VERSION_ID="1"
BOOM_OS_UNAME_PATTERN="nl1"
BOOM_OS_KERNEL_PATTERN="/vmlinux-%{version}"
BOOM_OS_INITRAMFS_PATTERN="/initramfs-%{version}.img"
BOOM_OS_ROOT_OPTS_LVM2="None"
BOOM_OS_ROOT_OPTS_BTRFS="rootflags=%{btrfs_subvolume}"
BOOM_OS_OPTIONS="root=%{root_device}"
