BOOM_OS_ID="f44fb528ff8360ad67e2fe0274750b838da0bd6a"
BOOM_OS_NAME="Red Hat Enterprise Linux"
BOOM_OS_SHORT_NAME="rhel"
BOOM_OS_VERSION="8.1 (Ootpa)"
BOOM_OS_VERSION_ID="8.1"
BOOM_OS_KERNEL_PATTERN="/vmlinuz-%{version}"
BOOM_OS_INITRAMFS_PATTERN="/initramfs-%{version}.img"
BOOM_OS_ROOT_OPTS_LVM2="rd.lvm.lv=%{lvm_root_lv}"
BOOM_OS_ROOT_OPTS_BTRFS="rootflags=%{btrfs_subvolume}"
BOOM_OS_OPTIONS="root=%{root_device} ro %{root_opts}"
BOOM_OS_TITLE="%{os_name} %{os_version_id} (%{version})"
BOOM_OS_OPTIONAL_KEYS=""
BOOM_OS_UNAME_PATTERN="el8"
